In [1]:
import numpy as np
import model
import pandas as pd


Example model, inventory system:

In [2]:
reorder_points = [10,10,10,10,20,20,20,20]
order_sizes = [50,60,80,100,50,60,80,100]


In [3]:
def create_X(reorder_points, order_sizes,n0):
    l = []
    for i in range(len(reorder_points)):
        np.random.seed(659)
        l.append(pd.DataFrame(model.run_experiments([reorder_points[i]], [order_sizes[i]], n0))['total_cost'])
    return np.array(l)
    

In [4]:
n0 = 160

X = create_X(reorder_points,order_sizes,n0)
print(X)
corr_coef = np.corrcoef(X[0], X[1])[0, 1]
print(corr_coef)

Iteration 100 of 160
Iteration 100 of 160
Iteration 100 of 160
Iteration 100 of 160
Iteration 100 of 160
Iteration 100 of 160
Iteration 100 of 160
Iteration 100 of 160
[[121.7 126.9 119.7 ... 124.6 124.3 121.3]
 [122.8 123.2 119.4 ... 119.5 128.6 122.8]
 [125.4 132.3 128.2 ... 128.2 123.1 125.5]
 ...
 [120.7 119.6 118.6 ... 117.7 129.7 121.2]
 [126.3 131.3 132.4 ... 129.  124.1 124.7]
 [132.1 141.1 129.9 ... 134.3 130.3 135.3]]
0.024473328811936684


In [170]:
def sample_variance(X):
    n = len(X[0])
    k = len(X)    
    som = 0
    for i in range(n):
        for j in range(k):
            t = np.subtract(X[j,i]-np.mean(X[:,i]),np.mean(X[j,:]))+np.mean(X)
            som += 2*t**2
    return som/(k-1)/(n-1)
        

In [171]:
print('Sample variance:')
print(sample_variance(X))

print('To find g value:')
print('(k-1) is:')
print(len(X)-1)
print('(k-1)*(n0-1) is:')
print((len(X)-1)*(len(X[0])-1))

Sample variance:
12.716964285714267
To find g value:
(k-1) is:
7
(k-1)*(n0-1) is:
28


In [175]:
d = 5
g = 2.89

def find_N(X,g,d):
    S2 = sample_variance(X)
    ans = max([len(X[0]),g**2*S2/d**2])
    return ans

find_N(X,g,d)

5

In [5]:
np.mean(X,axis=1)

array([123.863125, 123.996875, 127.058125, 132.553125, 119.334375,
       121.058125, 126.90375 , 134.308125])